/**
 * カテゴリ別カラーパレット（21 カテゴリ）
 *
 * アプリ内の「カテゴリ別使用時間」で使用される色。
 * ドーナツチャート、カテゴリアイコンの背景色などに適用。
 */

export const categoryColors = {
  light: {
    focus: '#10b981',
    productivity: '#3b82f6',
    education: '#8b5cf6',
    sns: '#f43f5e',
    games: '#ef4444',
    video: '#ec4899',
    music: '#a855f7',
    reading: '#6d28d9',
    entertainment: '#f59e0b',
    communication: '#6366f1',
    health: '#14b8a6',
    shopping: '#f97316',
    news: '#0369a1',
    finance: '#059669',
    photo: '#d946ef',
    food: '#ea580c',
    travel: '#0891b2',
    lifestyle: '#e11d48',
    tools: '#64748b',
    browser: '#0ea5e9',
    other: '#94a3b8',
  },
  dark: {
    focus: '#34d399',
    productivity: '#60a5fa',
    education: '#a78bfa',
    sns: '#fb7185',
    games: '#f87171',
    video: '#f472b6',
    music: '#c084fc',
    reading: '#a78bfa',
    entertainment: '#fbbf24',
    communication: '#818cf8',
    health: '#2dd4bf',
    shopping: '#fb923c',
    news: '#38bdf8',
    finance: '#34d399',
    photo: '#e879f9',
    food: '#fb923c',
    travel: '#22d3ee',
    lifestyle: '#fb7185',
    tools: '#94a3b8',
    browser: '#38bdf8',
    other: '#cbd5e1',
  },
} as const;

/** カテゴリの表示名（日本語） */
export const categoryLabels: Record<string, string> = {
  focus: '集中',
  productivity: '仕事・生産性',
  education: '教育',
  sns: 'SNS',
  games: 'ゲーム',
  video: '動画',
  music: '音楽',
  reading: '読書・マンガ',
  entertainment: 'エンタメ',
  communication: 'コミュニケーション',
  health: '健康',
  shopping: 'ショッピング',
  news: 'ニュース',
  finance: 'ファイナンス',
  photo: '写真・カメラ',
  food: 'フード',
  travel: '旅行・交通',
  lifestyle: 'ライフスタイル',
  tools: 'ツール',
  browser: 'ブラウザ',
  other: 'その他',
};

/** カテゴリアイコン名 (lucide-react / lucide-react-native) */
export const categoryIcons: Record<string, string> = {
  focus: 'Target',
  productivity: 'Briefcase',
  education: 'GraduationCap',
  sns: 'Heart',
  games: 'Gamepad2',
  video: 'Tv',
  music: 'Music',
  reading: 'BookOpen',
  entertainment: 'Joystick',
  communication: 'MessageCircle',
  health: 'Heart',
  shopping: 'ShoppingBag',
  news: 'Newspaper',
  finance: 'Wallet',
  photo: 'Camera',
  food: 'UtensilsCrossed',
  travel: 'Plane',
  lifestyle: 'Sparkles',
  tools: 'Wrench',
  browser: 'Globe',
  other: 'MoreHorizontal',
};
